harnessApiVersion: '1.0'
type: ROLLING
concurrencyStrategy: INFRA
envName: test
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - b4H42zzER-y1Q3hcwGH97Q
phases:
- type: KUBERNETES
  computeProviderName: Namespace dpt - Test Cluster -- referenceCloudProvider
  daemonSet: false
  infraDefinitionName: Test
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: referenceNativeK8sSvc
  statefulSet: false
  templateExpressions:
  - expression: ${Service}
    fieldName: serviceId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
      value: ${InfraDefinition_Kubernetes}
    - name: entityType
      value: SERVICE
  - expression: ${InfraDefinition_Kubernetes}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
rollbackPhases:
- type: KUBERNETES
  computeProviderName: Namespace dpt - Test Cluster -- referenceCloudProvider
  daemonSet: false
  infraDefinitionName: Test
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: referenceNativeK8sSvc
  statefulSet: false
  templateExpressions:
  - expression: ${Service}
    fieldName: serviceId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
      value: ${InfraDefinition_Kubernetes}
    - name: entityType
      value: SERVICE
  - expression: ${InfraDefinition_Kubernetes}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
templateExpressions:
- expression: ${Environment}
  fieldName: envId
  metadata:
  - name: artifactType
    value: DOCKER
  - name: relatedField
  - name: entityType
    value: ENVIRONMENT
- expression: ${Service}
  fieldName: serviceId
  metadata:
  - name: artifactType
    value: DOCKER
  - name: relatedField
    value: ${InfraDefinition_Kubernetes}
  - name: entityType
    value: SERVICE
- expression: ${InfraDefinition_Kubernetes}
  fieldName: infraDefinitionId
  metadata:
  - name: artifactType
    value: DOCKER
  - name: relatedField
  - name: entityType
    value: INFRASTRUCTURE_DEFINITION
templatized: true
userVariables:
- type: ENTITY
  description: Variable for Environment entity
  fixed: false
  mandatory: true
  name: Environment
- type: ENTITY
  description: Variable for Service entity in Rollback Rolling
  fixed: false
  mandatory: true
  name: Service
- type: ENTITY
  fixed: false
  mandatory: true
  name: InfraDefinition_Kubernetes

